[main]
resize-by-cells=no
resize-keep-grid=no
pad=12x12

# font stuffs
font=AdwaitaMonoNerdFont:size=11,NotoColorEmoji

include=~/.config/foot/colors.ini

[mouse]
hide-when-typing=yes

[scrollback]
multiplier=6

[csd]
size=0
border-width=0
border-color=5b5b5b

# adwaita dark modified a bit
[colors]
background=0b0b0b
foreground=deddda

regular0=1d1d1d
regular1=ed333b
regular2=57e389
regular3=ff7800
regular4=62a0ea
regular5=a151bc
regular6=5bc8af
regular7=deddda

bright0=9a9996
bright1=f66151
bright2=8ff0a4
bright3=ffa348
bright4=99c1f1
bright5=dc8add
bright6=93ddc2
bright7=f6f5f4

# adwaita light with better contrast
[colors2]
foreground=201e25
background=fcfcfc

regular0=fcfcfc
regular1=ed333b
regular2=008700
regular3=ff7800
regular4=5290ba
regular5=9141ac
regular6=5bc8af
regular7=9e9d9a

bright0=9a9996
bright1=f66151
bright2=7ff094
bright3=ffa348
bright4=6991d1
bright5=dc8add
bright6=83cdb2
bright7=f6f5f4
