[config]

[templates.fuzzel]
input_path = "~/.config/fuzzel/template.ini"
output_path = "~/.config/fuzzel/fuzzel.ini"

[templates.gtk4]
input_path = "~/.config/template.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.gtk3]
input_path = "~/.config/template.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.mako]
input_path = "~/.config/mako/template"
output_path = "~/.config/mako/config"

[templates.swaylock]
input_path = "~/.config/swaylock/template"
output_path = "~/.config/swaylock/config"

[templates.waybar_gtk] # keeps current mode's tooltips namely
input_path = "~/.config/template.css"
output_path = "~/.config/waybar/colors.css"
[templates.waybar_accents]
input_path = "~/.config/waybar/template.css"
output_path = "~/.config/waybar/accents.css"
mode = "Dark"                                # bar is always dark
