[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'Swww'
swww_options = ["--transition-type", "grow", "--transition-pos", "0.12,0.96"]

[config.reload_apps_list]
waybar = false # handled by darkman
# all others true by default

[templates.gtk4]
input_path = "~/.config/template.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.gtk3]
input_path = "~/.config/template.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.fuzzel]
input_path = "~/.config/fuzzel/template.ini"
output_path = "~/.config/fuzzel/fuzzel.ini"

[templates.waybar_gtk]
input_path = "~/.config/template.css"
output_path = "~/.config/waybar/colors.css"
[templates.waybar_accents]
input_path = "~/.config/waybar/template.css"
output_path = "~/.config/waybar/accents.css"
